const characters = [
  { name: "Hermes Vi Britannia", race: "Changeling", kingdom: "Britannia", status: "Vivo" },
  { name: "Zaros Rhazien Vi Britannia", race: "Vryloka", kingdom: "Britannia", status: "Morto" },
  { name: "Cedrico Ragnar", race: "Humano", kingdom: "Valhaz", status: "Morto" },
  { name: "Billy Florence", race: "Humano", kingdom: "Nenhum", status: "Vivo" },
  { name: "Tehen", race: "Elfo", kingdom: "Nenhum", status: "Vivo" },
  { name: "Mael Guinvern", race: "Elfo", kingdom: "Nenhum", status: "Morto" },
  { name: "Zeldris Dreifus", race: "Humano", kingdom: "Atreia", status: "Vivo" },
  { name: "Julius Vi Britannia", race: "Vryloka", kingdom: "Assuã", status: "Vivo" },
  { name: "Kojiro Kasaki", race: "Humano", kingdom: "Nenhum", status: "Vivo" },
  { name: "Alice Grimshaw", race: "Elfo", kingdom: "Nenhum", status: "Morto" },
  { name: "Morgott Skalgrim", race: "Gigante", kingdom: "Ashen", status: "Vivo" },
  { name: "Vendrick Valmor", race: "Humano", kingdom: "Reino", status: "Morto" },
  { name: "Gregory Windsor", race: "Humano", kingdom: "Morrowind", status: "Vivo" },
  { name: "Nebu Morningstar", race: "Changeling", kingdom: "Britannia", status: "Morto" },
  { name: "Heimdall Ragnar", race: "Humano", kingdom: "Valhaz", status: "Morto" },
  { name: "Ryuji Hanzo", race: "Humano", kingdom: "Nenhum", status: "Vivo" },
  { name: "Noctis Valemont", race: "Changeling", kingdom: "Drakória", status: "Vivo" },
  { name: "Galius Berkshire", race: "Humano", kingdom: "Drakória", status: "Vivo" },
  { name: "Syphros Rhazien", race: "Vryloka", kingdom: "Atreia", status: "Vivo" },
  { name: "Beru Hummel", race: "Humano", kingdom: "Heimar", status: "Vivo" },
  { name: "Rikigami Tenshou", race: "Humano", kingdom: "Nenhum", status: "Vivo" },
  { name: "Fynar", race: "Changeling", kingdom: "Britannia", status: "Vivo" },
  { name: "Rosnov Morningstar", race: "Changeling", kingdom: "Britannia", status: "Vivo" },
  { name: "Euphemia Rhazien Vi Britannia", race: "Vryloka", kingdom: "Britannia", status: "Vivo" },
  { name: "George Hummel", race: "Humano", kingdom: "Heimar", status: "Morto" },
  { name: "Teyocan Pachayoc", race: "Humano", kingdom: "Atreia", status: "Morto" }
];
